/**
 * Database types - will be generated by Supabase CLI
 * For now, we'll use placeholder types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      quizzes: {
        Row: {
          id: string
          creator_id: string
          title: string
          description: string | null
          settings: Json
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          creator_id: string
          title: string
          description?: string | null
          settings?: Json
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          creator_id?: string
          title?: string
          description?: string | null
          settings?: Json
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      questions: {
        Row: {
          id: string
          quiz_id: string
          question_order: number
          text: string
          type: string
          options: Json
          correct_answer: number | null
          time_limit: number
          points: number
          image_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          quiz_id: string
          question_order: number
          text: string
          type?: string
          options: Json
          correct_answer?: number | null
          time_limit?: number
          points?: number
          image_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          quiz_id?: string
          question_order?: number
          text?: string
          type?: string
          options?: Json
          correct_answer?: number | null
          time_limit?: number
          points?: number
          image_url?: string | null
          created_at?: string
        }
      }
      game_sessions: {
        Row: {
          id: string
          quiz_id: string
          pin: string
          status: string
          current_question_index: number
          max_participants: number
          settings: Json
          started_at: string | null
          finished_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          quiz_id: string
          pin: string
          status?: string
          current_question_index?: number
          max_participants?: number
          settings?: Json
          started_at?: string | null
          finished_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          quiz_id?: string
          pin?: string
          status?: string
          current_question_index?: number
          max_participants?: number
          settings?: Json
          started_at?: string | null
          finished_at?: string | null
          created_at?: string
        }
      }
      players: {
        Row: {
          id: string
          session_id: string
          nickname: string
          avatar_seed: string
          score: number
          is_active: boolean
          joined_at: string
        }
        Insert: {
          id?: string
          session_id: string
          nickname: string
          avatar_seed: string
          score?: number
          is_active?: boolean
          joined_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          nickname?: string
          avatar_seed?: string
          score?: number
          is_active?: boolean
          joined_at?: string
        }
      }
      player_answers: {
        Row: {
          id: string
          player_id: string
          question_id: string
          answer_index: number
          answered_at: string
          time_taken: number
          points_earned: number
          is_correct: boolean
        }
        Insert: {
          id?: string
          player_id: string
          question_id: string
          answer_index: number
          answered_at?: string
          time_taken: number
          points_earned?: number
          is_correct: boolean
        }
        Update: {
          id?: string
          player_id?: string
          question_id?: string
          answer_index?: number
          answered_at?: string
          time_taken?: number
          points_earned?: number
          is_correct?: boolean
        }
      }
    }
  }
}
